### ISSUE TITLE
Weird launch effect

### ISSUE THREAD

**Issue by Coronon** [rvandoosselaer/Blocks#8]
Yes, its me again ^^
So I have been playing around with it a lot and have all my weird behavior fixed, except one: When a character jumps onto a block and hits the edge he gets launched in the air **big** time.

Steps to reproduce:
Walk up right in front of a block, press 'w' and hold it, then press 'space bar'

I have had a deeper look into the matter and it seems as if the velocity of the object increases a lot in the collision tick (4 to > 9), so I implemented a custom PhysicsTickListener, but that only solves the problem **after** each tick, so you can still feel the boost very well. If you want to enable my 'fix' remove the comment on line 46 in ``PhysicsTickHandler``

Thank you for all your awesome support and all the work you are putting into this.

[Coronon-launchEffect.zip](https://github.com/rvandoosselaer/Blocks/files/3962411/Coronon-launchEffect.zip)

**Comment by rvandoosselaer** [comment]
Hi,
Cool that you are still using the framework and you got your issues almost tackled!
I don't think the issue you're having is due to a problem in the Blocks framework. I'm not an expert physics engines, or bullet in particular.
I'm an active member/contributor on the jmonkeyengine forum and I'm sure that people there can help you with the physics related issues; just post your issue on the [forum](https://hub.jmonkeyengine.org).

If not, I'm glad to reopen this issue and fix this in Blocks.
